plugins {
    id 'java'
}

group = 'com.example'
version = '1.0.0'

repositories {
    mavenCentral()
    maven {
        name = 'spigotmc'
        url = uri('https://hub.spigotmc.org/nexus/content/repositories/snapshots/')
    }
}

dependencies {
    compileOnly 'org.spigotmc:spigot-api:1.12.2-R0.1-SNAPSHOT'
    implementation 'mysql:mysql-connector-java:5.1.49'
}

sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

processResources {
    filesMatching('plugin.yml') {
        expand(version: project.version)
    }
}